import {useEffect,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowRight,ChevronUp,Dumbbell,Flame,HeartPulse,Menu,Shield,Target,Timer,Utensils,X,Zap} from 'lucide-react';
import {workouts,Workout,Exercise} from './data/workouts';

const nav=[['Início','inicio'],['Alimentação','alimentacao'],['Treino','treino'],['Muay Thai','condicionamento'],['Progressão','progressao']];
const Fade=({children,className=''}:{children:React.ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.45}}>{children}</motion.div>;
const Title=({tag,title,copy}:{tag:string,title:string,copy?:string})=><div className="mb-9 max-w-2xl"><p className="eyebrow mb-3">{tag}</p><h2 className="display text-3xl sm:text-5xl">{title}</h2>{copy&&<p className="muted mt-4 leading-7">{copy}</p>}</div>;

function Header(){const [open,setOpen]=useState(false);return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/8 bg-[#080a0bf2] backdrop-blur-xl"><div className="wrap flex h-16 items-center justify-between px-4 sm:h-[4.5rem]"><a href="#inicio" className="flex items-center gap-2 font-black tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-accent"><Dumbbell size={19}/></span>FORJA<span className="text-accent">.</span></a><nav aria-label="Navegação principal" className="hidden items-center gap-7 text-sm font-semibold text-zinc-400 md:flex">{nav.map(([n,id])=><a className="transition hover:text-white" href={'#'+id} key={id}>{n}</a>)}</nav><div className="flex items-center gap-2"><a href="#treino" className="hidden min-h-11 items-center rounded-xl bg-accent px-4 text-sm font-extrabold min-[390px]:inline-flex md:hidden">Meu treino</a><button aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} className="grid size-11 place-items-center rounded-xl border border-white/10 md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div><AnimatePresence>{open&&<motion.nav aria-label="Navegação mobile" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-white/8 bg-ink md:hidden"><div className="wrap px-4 py-3">{nav.map(([n,id])=><a className="flex min-h-12 items-center rounded-xl px-3 font-semibold text-zinc-300 hover:bg-white/5" href={'#'+id} key={id} onClick={()=>setOpen(false)}>{n}</a>)}</div></motion.nav>}</AnimatePresence></header>}

function Hero(){const stats=[['Musculação','5x / semana'],['Bike','Diariamente'],['Muay Thai','1x / semana'],['Corrida','Nenhuma']];return <section id="inicio" className="grain relative overflow-hidden pt-24"><div className="absolute -right-32 top-12 size-96 rounded-full bg-accent/15 blur-[110px]"/><div className="wrap relative px-4 py-12 sm:py-16 lg:py-24"><div className="grid items-center gap-10 lg:grid-cols-[1.08fr_.92fr]"><Fade><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-accent/25 bg-accent/10 px-3 py-1.5 text-xs font-bold text-orange-300"><Flame size={14}/> PLANO DE ALTA PERFORMANCE</div><h1 className="display max-w-3xl text-[clamp(2.25rem,6vw,4.75rem)]">FORÇA. MASSA.<br/><span className="accent-text">RESISTÊNCIA.</span> LUTA.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">Plano de treinamento focado em força, hipertrofia e resistência, mantendo condicionamento para o Muay Thai.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="#treino" className="inline-flex min-h-13 w-full items-center justify-center gap-2 rounded-xl bg-accent px-6 font-extrabold shadow-lg shadow-orange-950 transition hover:bg-orange-500 active:scale-95 sm:w-auto">Ver meu treino <ArrowRight size={19}/></a><a href="#alimentacao" className="inline-flex min-h-13 w-full items-center justify-center rounded-xl border border-white/12 bg-white/5 px-6 font-bold transition hover:bg-white/10 sm:w-auto">Ver alimentação</a></div></Fade><Fade className="hero-art w-full"><div className="hero-bar"/><div className="absolute right-5 top-5 z-10 rounded-xl border border-white/10 bg-black/35 p-3 backdrop-blur"><p className="text-xs font-black text-orange-300">FORÇA + FOCO</p><p className="text-sm font-bold">Sem atalhos.</p></div></Fade></div><div className="mt-10 grid grid-cols-1 gap-2 min-[360px]:grid-cols-2 sm:mt-12 lg:grid-cols-4">{stats.map(([a,b])=><div className="card p-4" key={a}><p className="text-xs text-zinc-500">{a}</p><p className="mt-1 font-extrabold">{b}</p></div>)}</div></div></section>}

function Objective(){const items=[[Target,'Força','Aumentar progressivamente a capacidade nos exercícios principais.'],[Dumbbell,'Hipertrofia','Gerar volume suficiente para estimular ganho de massa muscular.'],[HeartPulse,'Resistência','Melhorar resistência muscular e condicionamento.'],[Shield,'Muay Thai','Manter preparação física compatível com a prática semanal da luta.']];return <section className="section"><div className="wrap"><Title tag="01 / OBJETIVO" title="Construído para evoluir." copy="Ganhar força, resistência e massa muscular, mantendo condicionamento suficiente para praticar Muay Thai sem comprometer a recuperação."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{items.map(([Icon,t,d]:any)=><Fade className="card card-hover h-full p-5" key={t}><Icon className="mb-8 text-accent"/><h3 className="text-lg font-extrabold">{t}</h3><p className="muted mt-2 text-sm leading-6">{d}</p></Fade>)}</div></div></section>}

function Routine(){const r=[['Musculação','5x por semana'],['Bike','Deslocamento diário até a academia'],['Muay Thai','1x por semana'],['Corrida','Retirada'],['Descanso','Sábado e domingo']];return <section className="section border-y border-white/6 bg-white/[.015]"><div className="wrap"><Title tag="02 / ROTINA" title="Sua semana em movimento."/><div className="grid grid-cols-1 gap-3 min-[390px]:grid-cols-2 lg:grid-cols-5">{r.map(([a,b],i)=><div className="card p-5" key={a}><span className="text-xs font-black text-accent">0{i+1}</span><h3 className="mt-5 font-bold">{a}</h3><p className="muted mt-1 text-sm leading-5">{b}</p></div>)}</div></div></section>}

function Nutrition(){const meals=[['06:00','Pré-treino','Refeição pequena e leve: banana, pão, aveia, leite ou outra fonte de carboidrato.'],['07:00','Pós-treino','Super Shake.'],['Almoço','Refeição principal','Arroz, feijão, carne, frango ou ovos, legumes e verduras.'],['Tarde','Lanche','Refeição sólida com calorias e proteínas.'],['Jantar','Refeição principal','Arroz, feijão, carne, frango ou ovos, legumes e verduras.'],['Meta','Água','3 a 4 litros por dia, ajustando à sede, calor, treino e suor.']];return <section id="alimentacao" className="section"><div className="wrap"><Title tag="03 / COMBUSTÍVEL" title="Alimentação"/><div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><Fade className="card glow relative overflow-hidden p-6 sm:p-8"><Utensils className="text-accent"/><p className="eyebrow mt-6">07:00 — PÓS-TREINO</p><h3 className="mt-2 text-3xl font-black">Super Shake</h3><ul className="muted mt-5 space-y-2 text-sm leading-6"><li>80 g de Neston, Mucilon, Farinha Láctea ou Aveia</li><li>100 g de leite + 100 g de água</li><li>1 banana</li></ul><div className="mt-7 border-t border-white/10 pt-6"><p className="font-bold">Escolha uma fonte de proteína</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-white/5 p-4 text-sm"><b className="text-accent">OPÇÃO 01</b><br/>1 scoop de Whey Protein</div><div className="rounded-xl bg-white/5 p-4 text-sm"><b className="text-accent">OPÇÃO 02</b><br/>2 a 4 colheres de leite em pó desnatado</div></div></div></Fade><div className="relative space-y-3 before:absolute before:bottom-5 before:left-[19px] before:top-5 before:w-px before:bg-white/10">{meals.map(([time,t,d])=><div className="relative flex gap-4" key={time}><span className="z-10 mt-4 size-10 shrink-0 rounded-full border-4 border-ink bg-accent"/><div className="card w-full p-4"><p className="text-xs font-black text-accent">{time}</p><h4 className="font-bold">{t}</h4><p className="muted mt-1 text-sm leading-5">{d}</p></div></div>)}</div></div></div></section>}

function ExerciseCard({e,i}:{e:Exercise,i:number}){return <div className="card card-hover flex items-start gap-3 p-4"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-accent/12 text-xs font-black text-accent">{String(i+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><h4 className="font-bold leading-5 break-words">{e.name}</h4><p className="exercise-prescription mt-3 font-bold"><span>{e.sets} séries</span><span aria-hidden="true"> × </span><span>{e.reps} {e.unit}</span></p></div></div>}
function Day({w}:{w:Workout}){return <Fade><div className="card overflow-hidden"><div className="border-b border-white/8 p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{w.day}</p><h3 className="mt-2 max-w-2xl text-2xl font-black leading-tight sm:text-4xl">{w.title}</h3></div><span className="pill px-3 py-2 text-xs font-bold text-orange-300">{w.count}</span></div><div className="mt-6 rounded-xl bg-white/[.035] p-4"><p className="mb-2 text-xs font-black tracking-wider text-zinc-500">PREPARAÇÃO</p><ul className="grid gap-1 text-sm text-zinc-300 sm:grid-cols-2">{w.prep.map(x=><li key={x}>• {x}</li>)}</ul></div></div><div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-8">{w.exercises.map((e,i)=><ExerciseCard key={e.name} e={e} i={i}/>)}</div>{w.corrections&&<div className="m-4 mt-0 rounded-2xl border border-orange-500/20 bg-orange-500/[.06] p-5 sm:m-8 sm:mt-0"><p className="eyebrow">Correção de assimetria</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{w.corrections.map((e,i)=><ExerciseCard e={e} i={i} key={e.name}/>)}</div>{w.note&&<p className="mt-4 text-sm text-orange-200">Observação: {w.note}</p>}</div>}{!w.corrections&&w.note&&<div className="m-4 mt-0 rounded-xl border border-white/8 bg-white/[.03] p-4 text-sm text-zinc-300 sm:m-8 sm:mt-0"><b className="text-white">Cardio:</b> {w.note}</div>}</div></Fade>}
function Workouts(){const [selected,setSelected]=useState(0);return <section id="treino" className="section bg-white/[.015]"><div className="wrap"><Title tag="04 / PROGRAMA" title="Treino semanal" copy="Selecione o dia e leve seu plano com você. Cada sessão foi organizada para consulta rápida durante o treino."/><select aria-label="Selecionar dia" className="mb-4 h-13 w-full rounded-xl border border-white/10 bg-panel px-4 font-bold sm:hidden" value={selected} onChange={e=>setSelected(+e.target.value)}>{workouts.map((w,i)=><option value={i} key={w.day}>{w.day}</option>)}</select><div className="mb-5 hidden grid-cols-5 gap-2 sm:grid">{workouts.map((w,i)=><button onClick={()=>setSelected(i)} className={`min-h-12 rounded-xl border text-sm font-black transition ${selected===i?'border-accent bg-accent text-white':'border-white/8 bg-panel text-zinc-500 hover:text-white'}`} key={w.day}>{w.short}</button>)}</div><Day w={workouts[selected]}/></div></section>}

function Conditioning(){return <section id="condicionamento" className="section"><div className="wrap"><Title tag="05 / CARDIO" title="Condicionamento"/><div className="grid gap-4 md:grid-cols-2"><div className="card p-6"><Zap className="text-accent"/><h3 className="mt-8 text-2xl font-black">Bike</h3><p className="muted mt-3 leading-7">O deslocamento diário de bicicleta até a academia já faz parte do condicionamento. Não é necessário adicionar corrida.</p></div><div className="card p-6"><Flame className="text-accent"/><h3 className="mt-8 text-2xl font-black">Muay Thai <span className="text-base text-accent">1x / semana</span></h3><p className="muted mt-3 leading-7">Sexta-feira à noite ou sábado. Caso seja sexta, mantenha a musculação pela manhã.</p></div></div><div className="mt-4 rounded-2xl border border-orange-500/25 bg-orange-500/[.07] p-5 text-sm leading-6 text-orange-100"><b>Atenção à recuperação.</b> Se houver queda forte de desempenho, cansaço excessivo ou dores acumuladas, reduza primeiro o volume complementar da sexta-feira.</div></div></section>}

function Rest(){const r=[['Compostos pesados','90–180s'],['Outros compostos','90–120s'],['Isoladores','60–90s'],['Abdominal','45–60s'],['Panturrilha','45–60s']];return <section className="section border-y border-white/6 bg-white/[.015]"><div className="wrap"><Title tag="06 / RECUPERAÇÃO" title="Descanso entre séries"/><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{r.map(([a,b])=><div className="card p-4" key={a}><Timer size={18} className="text-accent"/><p className="mt-5 text-sm font-bold">{a}</p><p className="mt-1 text-xl font-black">{b}</p></div>)}</div><p className="muted mt-5 max-w-3xl text-sm leading-6">Em Agachamento, Supino, Remada e Desenvolvimento, descanse mais quando necessário para preservar carga, força, técnica e qualidade da execução.</p></div></section>}

function Progression(){return <section id="progressao" className="section"><div className="wrap"><Title tag="07 / PROGRESSÃO" title="Ganhe repetições. Depois, carga."/><div className="card glow grid overflow-hidden lg:grid-cols-2"><div className="p-6 sm:p-9"><p className="eyebrow">Agachamento Livre · 4×6–8</p><div className="my-8 flex items-center justify-between text-3xl font-black sm:text-5xl"><span>6</span><ArrowRight className="text-accent"/><span>7</span><ArrowRight className="text-accent"/><span>8</span></div><p className="muted leading-7">Ao completar 8 repetições com boa execução: aumente a carga, volte para 6 repetições e repita o processo.</p></div><div className="border-t border-white/8 bg-white/[.025] p-6 sm:p-9 lg:border-l lg:border-t-0"><div className="space-y-3">{[['Semana 1','60 kg — 4×6'],['Semana 2','60 kg — 4×7'],['Semana 3','60 kg — 4×8']].map(([a,b])=><div className="flex justify-between gap-3 border-b border-white/8 pb-3" key={a}><span className="muted text-sm">{a}</span><b>{b}</b></div>)}</div><div className="mt-5 rounded-xl bg-accent p-4"><p className="text-xs font-black">PRÓXIMA PROGRESSÃO</p><p className="mt-1 font-bold">Aumentar a carga e voltar para 4×6</p></div></div></div></div></section>}

function Summary(){return <section className="section bg-white/[.015]"><div className="wrap"><Title tag="08 / VISÃO GERAL" title="Resumo semanal"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{workouts.map(w=><div className="card p-5" key={w.day}><p className="eyebrow">{w.short}</p><h3 className="mt-4 min-h-16 font-bold leading-5">{w.title}</h3><p className="mt-6 border-t border-white/8 pt-4 text-xs font-bold text-zinc-400">{w.count}</p></div>)}</div></div></section>}
function App(){const [top,setTop]=useState(false);useEffect(()=>{const f=()=>setTop(scrollY>650);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <><Header/><main><Hero/><Objective/><Routine/><Nutrition/><Workouts/><Conditioning/><Rest/><Progression/><Summary/></main><footer className="border-t border-white/8 px-4 py-12 text-center"><Dumbbell className="mx-auto text-accent"/><p className="mt-4 font-black">FORÇA + RESISTÊNCIA + HIPERTROFIA + MUAY THAI</p><p className="muted mt-2 text-sm">Consistência, progressão e recuperação.</p></footer>{top&&<button aria-label="Voltar ao topo" onClick={()=>scrollTo({top:0,behavior:'smooth'})} className="fixed bottom-4 right-4 z-40 grid size-12 place-items-center rounded-full bg-accent shadow-xl shadow-black/50 md:hidden"><ChevronUp/></button>}</>};export default App;
